#!/usr/bin/env bash
# mongodb.sh — provision MongoDB.
#
# Three deployment modes:
#
#   local-standalone   1- or 2-VM clusters. M1 only. Auth on; bind 0.0.0.0
#                      when 2-VM (M2 needs to reach it) or 127.0.0.1 when 1-VM.
#
#   local-rs           3+ VM clusters. Each of the first 3 nodes runs a
#                      replica-set member (replSetName=elchi-rs, keyfile auth).
#                      M1 owns rs.initiate(); secondaries just start with
#                      --replSet and wait.
#
#   external           Operator-supplied URI. No mongo install on this host.
#                      URI is written into secrets.env so backend reads it.
#
# ----- transition matrix (cluster size growth via add-node) ------------
#
# is_mongo_node (lib/topology.sh:163-169) caps mongo at the first 3 nodes:
#   N=1|2  → only M1 runs mongo
#   N>=3   → M1+M2+M3 form the replica set; M4..MN are mongo-less
#
# add-node grows N by exactly 1 per call. Transitions and the function
# chain that handles each:
#
#   1 → 2  (standalone, no mongo change)
#       M2 phase 1 sees `runs_mongo: false`, skips mongo block entirely.
#       M1's bootstrap_auth fast path notes mode=standalone matches and
#       returns early. initiate_replica_set early-returns at size<3.
#
#   2 → 3  (STANDALONE → REPLICA SET migration — the interesting case)
#       M1 phase 1: setup_replica_member. install_package no-op (already
#       there), write_dropin idempotent, _apply_keyfile_perms now runs
#       (keyfile gets generated by secrets::generate at orchestrator time
#       and bundled to M2/M3). Then bootstrap_auth rs's fast path detects
#       `mode=rs && current_mode=standalone`, calls configure_conf rs
#       (writes replSetName + keyFile into /etc/mongod.conf) and
#       restart_service. Mongod comes back in RS-uninitiated state.
#       M2 + M3 phase 1: setup_replica_member fresh path — apt installs
#       mongodb-org for the first time, configure_conf rs, mongod starts
#       in RS-uninitiated state.
#       Mid-orchestration: initiate_replica_set issues rs.initiate with
#       all 3 members, waits for 1 PRIMARY + 2 SECONDARY. M1's existing
#       data is preserved and replicated to M2/M3 via initial sync.
#       Operator-visible cost: ~10-30s write-availability gap during
#       M1's RS-mode restart.
#
#   3 → 4 (and 4 → 5+)  (no mongo change)
#       M_new sees `runs_mongo: false`, skips mongo block. M1+M2+M3 are
#       reconciled by the M1 phase 1 fast path which finds mode=rs +
#       config=rs and returns early. initiate_replica_set's idempotent
#       branch lists current members, sees no missing, returns.
#
# elchi-stack add-node renders a preview describing the impact above
# before exec'ing install.sh, so operators always see which transition
# class they're entering and the expected downtime envelope.
#

# MongoDB version policy: a single canonical major (8.0) across every
# supported distro. The previous OS-aware auto-pick (Ubuntu 24 → 8.0,
# Ubuntu 22 → 7.0, RHEL → 7.0) was a drift source: even when the
# homogeneity preflight is green for the cluster's OS major, two
# subtly-different point releases (e.g. Ubuntu 22.04.4 vs 22.04.5) could
# still resolve to different mongo majors on a re-image. A 3-member RS
# straddling mongo 7.0 + 8.0 fails wire-protocol negotiation and binary
# upgrade ordering — the kind of failure that surfaces hours after
# install when something restarts.
#
# 8.0 is current-GA and has apt/yum repos for every distro this stack
# supports per `preflight::_check_supported_version`:
#   * Ubuntu 22.04 (jammy), 24.04 (noble)
#   * Debian 12 (bookworm)
#   * RHEL / Rocky / Alma / Oracle 9
# Distros we deliberately do NOT support:
#   * Debian 11 (bullseye), Ubuntu 20.04 (focal) — Mongo 8.0 isn't
#     published for them, and we refuse to silently fall back to 7.0
#     (silent fallback was the original drift bug).
#   * RHEL / Rocky / Alma / Oracle 8 — Mongo 8.0 IS published for it
#     but our systemd unit hardening (ProtectKernelLogs, ProtectClock,
#     ProcSubset, …) requires systemd ≥ 247 which RHEL 8 ships older.
# Operators on those releases have to update the OS first; this also
# keeps the homogeneity preflight meaningful (no "M1 jammy gets 7.0,
# M2 jammy gets 8.0 because operator rebuilt with an older repo
# cache" surprise).
#
# Operator override remains via --mongo-version=X.Y for off-label
# experiments; the apt/yum repo probe below fails fast if that combo
# isn't actually published.

# ----- version resolver ---------------------------------------------------
mongodb::resolve_version() {
  local explicit=${ELCHI_MONGO_VERSION:-}
  if [ -n "$explicit" ] && [ "$explicit" != "auto" ]; then
    ELCHI_MONGO_VERSION_RESOLVED=$explicit
    log::info "using operator-supplied MongoDB version: ${ELCHI_MONGO_VERSION_RESOLVED}"
  else
    ELCHI_MONGO_VERSION_RESOLVED=8.0
    log::info "MongoDB ${ELCHI_MONGO_VERSION_RESOLVED} (cluster-wide canonical default; override with --mongo-version=X.Y)"
  fi
  export ELCHI_MONGO_VERSION_RESOLVED
}

# ----- package install ---------------------------------------------------
mongodb::install_package() {
  if command -v mongod >/dev/null 2>&1; then
    log::info "mongod already present, skipping package install"
    return
  fi
  case "$ELCHI_OS_FAMILY" in
    debian) mongodb::_install_debian ;;
    rhel)   mongodb::_install_rhel ;;
  esac
}

mongodb::_install_debian() {
  local v=$ELCHI_MONGO_VERSION_RESOLVED
  log::info "installing mongodb-org ${v} from official repo"
  preflight::wait_apt_lock 600 || true
  apt-get install -y -qq gnupg ca-certificates curl
  install -d -m 0755 /etc/apt/keyrings

  local codename=$ELCHI_OS_CODENAME
  [ -n "$codename" ] || codename=jammy

  # Probe before writing any apt source. A 404 here means the operator's
  # version+OS combo isn't published — fail with a clear message instead
  # of an opaque "apt-get update" error 30 seconds later.
  local probe="https://repo.mongodb.org/apt/${ELCHI_OS_ID}/dists/${codename}/mongodb-org/${v}/Release"
  if ! curl -fsI --max-time 15 "$probe" >/dev/null 2>&1; then
    die "MongoDB ${v} has no apt repo for ${ELCHI_OS_ID} ${codename}. The default is 8.0 — if you reached here with an --mongo-version override, drop the flag (or use --mongo-version=8.0 explicitly)."
  fi

  mongodb::_clean_stale_debian_repos "$v"

  local keyring="/etc/apt/keyrings/mongodb-server-${v}.gpg"
  curl -fsSL "https://pgp.mongodb.com/server-${v}.asc" \
    | gpg --dearmor -o "$keyring"
  chmod 0644 "$keyring"

  local component=multiverse
  [ "$ELCHI_OS_ID" = "debian" ] && component=main

  cat > "/etc/apt/sources.list.d/mongodb-org-${v}.list" <<EOF
deb [ signed-by=${keyring} ] https://repo.mongodb.org/apt/${ELCHI_OS_ID} ${codename}/mongodb-org/${v} ${component}
EOF

  preflight::wait_apt_lock 600 || true
  apt-get update -qq
  preflight::wait_apt_lock 600 || true
  apt-get install -y -qq mongodb-org
}

mongodb::_install_rhel() {
  local v=$ELCHI_MONGO_VERSION_RESOLVED
  log::info "installing mongodb-org ${v} from official repo"
  local pm
  pm=$(command -v dnf || command -v yum)

  local major=${ELCHI_OS_VERSION%%.*}
  local base="https://repo.mongodb.org/yum/redhat/${major}/mongodb-org/${v}/x86_64"

  # repomd.xml existing only proves MongoDB created the repo SKELETON for
  # this EL major — it does NOT prove the server packages are published.
  if ! curl -fsI --max-time 15 "${base}/repodata/repomd.xml" >/dev/null 2>&1; then
    die "MongoDB ${v} has no yum repo for RHEL ${major}. Re-run with --mongo-version=8.0."
  fi

  mongodb::_clean_stale_rhel_repos "$v"

  cat > "/etc/yum.repos.d/mongodb-org-${v}.repo" <<EOF
[mongodb-org-${v}]
name=MongoDB Repository
baseurl=${base}/
gpgcheck=1
enabled=1
gpgkey=https://pgp.mongodb.org/server-${v}.asc
EOF

  # Import the repo signing key explicitly into the RPM keyring. dnf's
  # gpgkey= auto-import is unreliable when a STALE mongodb key from a
  # previous version (or a half-finished earlier attempt) is already
  # present: dnf decides "a MongoDB key exists" and skips importing the
  # current one, then gpgcheck fails with
  #   "The GPG keys ... are already installed but they are not correct
  #    for this package" / "Public key for mongodb-org-server ... is not
  #    installed"
  # even though the packages themselves are perfectly valid. An explicit
  # rpm --import of the version-correct key lands it regardless of
  # whatever else is in the keyring (idempotent — re-importing the same
  # key is a no-op). Mirrors what the Debian path already does via
  # `gpg --dearmor -o keyring`.
  rpm --import "https://pgp.mongodb.org/server-${v}.asc" 2>/dev/null \
    || log::warn "could not import MongoDB ${v} GPG key — gpgcheck may fail below"

  # Run the real install and let the package manager's own output stream
  # live. If it fails because the server metapackage isn't in the repo
  # (the EL-major-just-released case: MongoDB publishes client tools
  # weeks before mongodb-org-server), dnf prints "No match for argument:
  # mongodb-org" — translate that one specific failure into an
  # actionable message. Any other failure (deps, gpg, network) keeps
  # dnf's own output above + a generic die.
  #
  # NB: an earlier revision tried to PRE-detect this by parsing
  # repomd.xml → primary.xml ourselves. RHEL repodata uses zchunk +
  # hashed filenames + multiple <location> entries, and that parse
  # mis-read a fully-populated el9 repo as empty — false-blocking a
  # valid AlmaLinux 9 install. Letting `dnf install` be the single
  # source of truth avoids re-implementing the metadata reader.
  if ! "$pm" install -y mongodb-org; then
    die "mongodb-org install failed on ${ELCHI_OS_ID} ${ELCHI_OS_VERSION}.
       If dnf reported 'No match for argument: mongodb-org' just above, MongoDB
       has not published server RPMs for ${ELCHI_OS_ID} ${major} yet (the el${major}
       repo ships only client tools). In that case:
         1) install on RHEL/Rocky/Alma/Oracle 9 (server fully published), OR
         2) use an external mongo:
              --mongo=external --mongo-uri=mongodb://user:pass@host:27017/elchi
       Any other dnf error above (dependencies / GPG / network) is a separate
       failure — fix it and re-run."
  fi
}

mongodb::_clean_stale_debian_repos() {
  local keep=$1 f
  for f in /etc/apt/sources.list.d/mongodb-org-*.list; do
    [ -e "$f" ] || continue
    [ "$(basename "$f")" = "mongodb-org-${keep}.list" ] || rm -f "$f"
  done
  for f in /etc/apt/keyrings/mongodb-server-*.gpg; do
    [ -e "$f" ] || continue
    [ "$(basename "$f")" = "mongodb-server-${keep}.gpg" ] || rm -f "$f"
  done
}

mongodb::_clean_stale_rhel_repos() {
  local keep=$1 f
  for f in /etc/yum.repos.d/mongodb-org-*.repo; do
    [ -e "$f" ] || continue
    [ "$(basename "$f")" = "mongodb-org-${keep}.repo" ] || rm -f "$f"
  done
}

# ----- mongod.conf rendering ---------------------------------------------
# Produce /etc/mongod.conf with our managed bind/auth/keyFile/replSet
# block. Idempotent — overwrites a previous block with the same markers.
#
# bindIp:
#   * 1-VM standalone:  127.0.0.1
#   * 2-VM standalone:  0.0.0.0 (M2 reaches over LAN)
#   * 3+-VM RS:         0.0.0.0 always
mongodb::configure_conf() {
  local mode=$1   # "standalone" | "rs"
  local conf=/etc/mongod.conf
  [ -f "$conf" ] || die "/etc/mongod.conf not found after install"

  # Determine bindIp from cluster size.
  local size=1
  if [ -f "${ELCHI_ETC}/topology.full.yaml" ]; then
    size=$(awk '/^cluster:/{f=1; next} f && /^[[:space:]]+size:/{print $2; exit}' "${ELCHI_ETC}/topology.full.yaml")
  fi
  local bind_ip=127.0.0.1
  if [ "${size:-1}" -ge 2 ] 2>/dev/null; then
    bind_ip=0.0.0.0
  fi

  # Strip any previous managed block.
  if grep -q '# BEGIN elchi-stack managed' "$conf"; then
    sed -i '/# BEGIN elchi-stack managed/,/# END elchi-stack managed/d' "$conf"
  fi

  # Trim trailing blank lines so repeat runs don't accumulate them.
  # Without this, every rerun grows mongod.conf by one empty line and
  # systemd::reconcile_external sees a fingerprint diff → spurious mongod
  # restart on M2/M3 (M1 escapes only because its fingerprint is captured
  # before configure_conf runs, via setup_replica_member's start_service
  # → bootstrap_auth ordering).
  sed -i -e :a -e '/^$/{$d;N;ba' -e '}' "$conf"

  # Update bindIp in the existing net: section. mongod.conf is YAML.
  if grep -Eq '^[[:space:]]*bindIp:' "$conf"; then
    sed -i "s|^[[:space:]]*bindIp:.*|  bindIp: ${bind_ip}|" "$conf"
  fi

  {
    echo '# BEGIN elchi-stack managed'
    echo 'security:'
    echo '  authorization: enabled'
    if [ "$mode" = "rs" ]; then
      echo "  keyFile: ${ELCHI_MONGO}/keyfile"
      echo 'replication:'
      echo '  replSetName: elchi-rs'
    fi
    echo '# END elchi-stack managed'
  } >> "$conf"
}

# ----- service start + reachability --------------------------------------
mongodb::start_service() {
  # mongod is package-shipped; we only own the elchi block in
  # /etc/mongod.conf and the keyfile. Reconcile against those so a
  # config edit (auth flip, replSet change) triggers restart on rerun.
  systemd::reconcile_external mongod.service mongod \
    /etc/mongod.conf \
    "${ELCHI_MONGO}/keyfile"
  wait_for_tcp 127.0.0.1 27017 30 \
    || die "mongod did not become reachable on 127.0.0.1:27017 within 30s"
}

mongodb::restart_service() {
  systemctl restart mongod
  wait_for_tcp 127.0.0.1 27017 30 \
    || die "mongod did not come back after restart"
}

# ----- mongosh wrapper ---------------------------------------------------
mongodb::_mongosh() {
  if command -v mongosh >/dev/null 2>&1; then
    mongosh "$@"
  elif command -v mongo >/dev/null 2>&1; then
    mongo "$@"
  else
    die "neither mongosh nor mongo client found — install mongodb-mongosh"
  fi
}

# Run a JS snippet against the LOCAL mongod without auth. Used during
# first-time bootstrap before authorization is turned on.
mongodb::eval_noauth() {
  local js=$1 out
  out=$(mongodb::_mongosh --quiet --host 127.0.0.1 --port 27017 --eval "$js" 2>&1) || {
    printf '%s\n' "$out" >&2
    return 1
  }
  if ! printf '%s' "$out" | grep -q 'EVAL_OK'; then
    printf '[mongodb::eval_noauth] EVAL_OK sentinel missing — output:\n%s\n' "$out" >&2
    return 1
  fi
  printf '%s\n' "$out" | grep -v '^EVAL_OK$' | sed 's/^/  [mongosh] /' || true
}

# Run a JS snippet authenticated as the root user. Reads creds from
# /etc/elchi/mongo/root.env (M1 only).
mongodb::eval_root() {
  local js=$1 user pwd out
  user=$(grep '^MONGO_ROOT_USERNAME=' "${ELCHI_MONGO}/root.env" | cut -d= -f2-)
  pwd=$(grep  '^MONGO_ROOT_PASSWORD=' "${ELCHI_MONGO}/root.env" | cut -d= -f2-)
  out=$(mongodb::_mongosh --quiet --host 127.0.0.1 --port 27017 \
          -u "$user" -p "$pwd" --authenticationDatabase admin --eval "$js" 2>&1) || {
    printf '%s\n' "$out" >&2
    return 1
  }
  if ! printf '%s' "$out" | grep -q 'EVAL_OK'; then
    printf '[mongodb::eval_root] EVAL_OK sentinel missing — output:\n%s\n' "$out" >&2
    return 1
  fi
  printf '%s\n' "$out" | grep -v '^EVAL_OK$' | sed 's/^/  [mongosh] /' || true
}

# ----- bootstrap auth (standalone + RS-primary path) ---------------------
mongodb::bootstrap_auth() {
  local mode=$1   # "standalone" | "rs"

  # Defensive guard: the detection probe below opens a mongosh connection
  # to 127.0.0.1:27017. If mongod's restart from `start_service` /
  # `restart_service` is still in flight (TCP socket bound but not yet
  # accepting auth), the probe gets a connection-refused / handshake
  # error that doesn't match any of our expected "auth wall" patterns —
  # auth_enabled stays 0, the function falls through to first-install
  # path, and the next mongosh.eval_noauth call dies with an opaque
  # MongoNetworkError which strict-mode (`set -Eeuo pipefail`) turns into
  # a generic install failure. Wait for the port to actually be ready
  # so transient timing issues surface as a clear "mongod not listening"
  # die instead.
  wait_for_tcp 127.0.0.1 27017 30 \
    || die "mongod not listening on 127.0.0.1:27017 — bootstrap_auth cannot proceed (check 'systemctl status mongod' + 'tail /var/log/mongodb/mongod.log')"

  # Detect current state. mongosh exit codes are unreliable when --eval
  # hits an auth wall, so we inspect output.
  local detect auth_enabled=0
  detect=$(mongodb::_mongosh --quiet --host 127.0.0.1 --port 27017 \
             --eval 'db.adminCommand({listDatabases:1})' 2>&1 || true)
  case "$detect" in
    *Unauthorized*|*"not authorized"*|*"requires authentication"*|*"AuthenticationFailed"*|*"Authentication failed"*)
      auth_enabled=1 ;;
  esac

  # Fast path: rerun with auth + creds in place — leave alone UNLESS
  # the caller wants RS mode and the current mongod.conf is still
  # standalone. This is the 2-node → 3-node growth path: an earlier
  # install put M1 in standalone with auth on, the new install asks
  # for `mode=rs` but the fast path used to short-circuit before
  # `configure_conf rs` ever ran. Net effect: mongod kept booting
  # without --replSet, so rs.initiate() crashed with "This node was
  # not started with replication enabled". Detect the mismatch here
  # and flip the config + restart before returning.
  if [ "$auth_enabled" = "1" ] && [ -f "${ELCHI_MONGO}/root.env" ]; then
    local app_user
    app_user=$(secrets::value ELCHI_MONGO_USERNAME)
    if [ -n "$app_user" ]; then
      local current_mode=standalone
      if grep -Eq '^[[:space:]]*replSetName:' /etc/mongod.conf 2>/dev/null; then
        current_mode=rs
      fi
      if [ "$mode" = "rs" ] && [ "$current_mode" != "rs" ]; then
        log::info "mongo: auth on, but config is standalone — flipping to RS (cluster grew)"
        mongodb::configure_conf rs
        mongodb::restart_service
        log::ok "mongo: flipped from standalone to RS member"
      elif [ "$mode" = "standalone" ] && [ "$current_mode" != "standalone" ]; then
        log::info "mongo: auth on, but config is RS — flipping to standalone (cluster shrank)"
        mongodb::configure_conf standalone
        mongodb::restart_service
        log::ok "mongo: flipped from RS to standalone"
      else
        log::info "mongo auth already configured (mode=${mode}) — preserving"
      fi
      return
    fi
  fi

  # Hard-stuck path: auth on but no credentials we can use. Operator
  # must intervene; refusing to "guess" prevents data loss.
  if [ "$auth_enabled" = "1" ] && [ ! -f "${ELCHI_MONGO}/root.env" ]; then
    die "mongo has authorization enabled but root credentials are missing. Manual recovery required: stop mongod, wipe /var/lib/mongodb, remove the elchi-stack managed block from /etc/mongod.conf, restart, and re-run install.sh."
  fi

  # First-install path: auth not yet on. Create root + app users.
  local root_user root_pwd app_user app_pwd db_name
  root_user=$(secrets::value ELCHI_MONGO_ROOT_USERNAME)
  root_pwd=$(secrets::value ELCHI_MONGO_ROOT_PASSWORD)
  app_user=$(secrets::value ELCHI_MONGO_USERNAME)
  app_pwd=$(secrets::value ELCHI_MONGO_PASSWORD)
  db_name=${ELCHI_MONGO_DATABASE:-elchi}
  [ -n "$root_user" ] && [ -n "$root_pwd" ] || die "mongo creds missing from secrets.env"

  log::info "creating mongo root + app users (first run)"
  # `use admin;` doesn't work in mongosh 2.x --eval mode — getSiblingDB
  # is the deterministic form.
  mongodb::eval_noauth "
    var adminDb = db.getSiblingDB('admin');
    if (!adminDb.getUser('${root_user}')) {
      adminDb.createUser({user: '${root_user}', pwd: '${root_pwd}', roles: [{role: 'root', db: 'admin'}]});
    } else {
      adminDb.changeUserPassword('${root_user}', '${root_pwd}');
    }
    if (!adminDb.getUser('${app_user}')) {
      adminDb.createUser({user: '${app_user}', pwd: '${app_pwd}', roles: [{role: 'readWrite', db: '${db_name}'}, {role: 'dbAdmin', db: '${db_name}'}]});
    } else {
      adminDb.changeUserPassword('${app_user}', '${app_pwd}');
    }
    print('EVAL_OK');
  " || die "failed to bootstrap mongo users"

  # Flip auth (and replSet for RS mode) on.
  mongodb::configure_conf "$mode"
  mongodb::restart_service
}

# ----- replica-set initiate (M1-only) ------------------------------------
# Called BETWEEN install phase 1 (mongods up everywhere) and phase 2
# (services that talk to the RS). Issues a single rs.initiate() with the
# full member list — the standard MongoDB pattern — then waits until M1
# is PRIMARY and M2 + M3 are SECONDARY. By the time this returns, the RS
# is fully formed and any client connecting with `?replicaSet=elchi-rs`
# sees a healthy 3-member topology.
#
# Idempotent: rerunning when the RS is already initialized is a no-op.
mongodb::initiate_replica_set() {
  local size
  size=$(awk '/^cluster:/{f=1; next} f && /^[[:space:]]+size:/{print $2; exit}' "${ELCHI_ETC}/topology.full.yaml")
  if [ "$size" -lt 3 ] 2>/dev/null; then
    log::info "cluster size ${size} — standalone mongo, no RS to initiate"
    return 0
  fi

  log::step "Initiating mongo replica set (3 members)"

  local n1 n2 n3
  n1=$(awk '/^  - index: 1/{f=1; next} f && /^    host:/{print $2; exit}' "${ELCHI_ETC}/topology.full.yaml")
  n2=$(awk '/^  - index: 2/{f=1; next} f && /^    host:/{print $2; exit}' "${ELCHI_ETC}/topology.full.yaml")
  n3=$(awk '/^  - index: 3/{f=1; next} f && /^    host:/{print $2; exit}' "${ELCHI_ETC}/topology.full.yaml")

  # Phase 1 of the orchestration is supposed to have started mongod on
  # every member already. Re-verify here as a safety net before issuing
  # rs.initiate — the alternative is rs.initiate succeeding but failing
  # the implicit majority count when secondaries don't show up, which
  # leaves the RS in a half-initialized state that's painful to debug.
  log::info "verifying all mongods are reachable"
  wait_for_tcp "$n1" 27017 60 || die "M1 (${n1}:27017) mongod not reachable"
  wait_for_tcp "$n2" 27017 120 || die "M2 (${n2}:27017) mongod not reachable"
  wait_for_tcp "$n3" 27017 120 || die "M3 (${n3}:27017) mongod not reachable"

  # Idempotent check: is the RS already initialized?
  local rs_state
  rs_state=$(mongodb::eval_root "
    try {
      var s = rs.status();
      print('STATE:' + s.myState);
    } catch (e) {
      if (e.codeName === 'NotYetInitialized') {
        print('STATE:NEW');
      } else {
        print('STATE:ERR:' + e.message);
      }
    }
    print('EVAL_OK');
  " 2>&1 || true)

  if printf '%s' "$rs_state" | grep -q 'STATE:1\|STATE:2'; then
    log::info "replica set already initialized — syncing member list with topology"
    # An earlier half-broken install (e.g. one that ran rs.initiate with
    # only M1 before the cluster grew) can leave the RS in a state where
    # M1 is PRIMARY but M2/M3 are NOT in rs.status().members at all. The
    # convergence wait below would then time out forever (secondaryCount
    # stays at 0) without a useful clue. Reconcile the configured member
    # set against topology and add the missing ones.
    # NB: mongodb::eval_root prefixes every output line with `  [mongosh] `
    # before returning it (so multi-line script output is clearly tagged
    # in install.log). A line-anchored `grep '^MEMBERS:'` therefore never
    # matches; use sed to strip the prefix and capture only the payload
    # after the sentinel.
    local existing
    existing=$(mongodb::eval_root "
      var s = rs.status();
      print('MEMBERS:' + s.members.map(m => m.name).join(','));
      print('EVAL_OK');
    " 2>/dev/null | sed -n 's/.*MEMBERS://p' | head -1 || true)
    log::info "RS currently configured with: ${existing:-<empty>}"

    local h
    for h in "$n1" "$n2" "$n3"; do
      case ",${existing}," in
        *",${h}:27017,"*)
          ;;
        *)
          local pri=1
          [ "$h" = "$n1" ] && pri=2
          log::info "adding missing member ${h}:27017 to RS (priority=${pri})"
          mongodb::eval_root "
            rs.add({host: '${h}:27017', priority: ${pri}});
            print('EVAL_OK');
          " || die "rs.add(${h}) failed — try 'mongosh ... --eval rs.status()' for state"
          ;;
      esac
    done
  else
    mongodb::eval_root "
      rs.initiate({
        _id: 'elchi-rs',
        members: [
          {_id: 0, host: '${n1}:27017', priority: 2},
          {_id: 1, host: '${n2}:27017', priority: 1},
          {_id: 2, host: '${n3}:27017', priority: 1}
        ]
      });
      print('EVAL_OK');
    " || die "rs.initiate() failed"
    log::ok "rs.initiate() issued"
  fi

  # Wait until M1 is PRIMARY and M2 + M3 are SECONDARY. Without this gate
  # the next phase's registry / control-plane services would still race
  # against an electing RS — driver retries cushion this in practice but
  # the install logs would be noisy with reconnects. 60s is generous;
  # election typically settles in 5–15s on a healthy network.
  log::info "waiting for RS to converge (M1=PRIMARY, M2/M3=SECONDARY)"
  local i out primary_count secondary_count
  for i in $(seq 1 60); do
    # `mongodb::eval_root` returns non-zero when mongod is briefly
    # unreachable (mid-election the primary can refuse new connections
    # for a few hundred ms). Under `set -Eeuo pipefail` that would kill
    # the whole orchestrator — we must absorb transient errors and just
    # retry on the next tick. `|| true` swallows the function exit code;
    # `2>/dev/null` hides the noisy "MongoNetworkError" backtraces from
    # the operator's screen during the few seconds it takes for the new
    # primary to start serving rs.status() reads again.
    # `grep -oE` strips mongodb::eval_root's `  [mongosh] ` prefix and
    # returns only the matched "P:N S:M" payload — same parsing fix as
    # the member-sync block above.
    out=$(mongodb::eval_root "
      var s = rs.status();
      var p = s.members.filter(m => m.stateStr === 'PRIMARY').length;
      var sec = s.members.filter(m => m.stateStr === 'SECONDARY').length;
      print('P:' + p + ' S:' + sec);
      print('EVAL_OK');
    " 2>/dev/null | grep -oE 'P:[0-9]+ S:[0-9]+' | head -1 || true)
    primary_count=$(printf '%s' "$out" | sed -n 's/^P:\([0-9]*\).*/\1/p')
    secondary_count=$(printf '%s' "$out" | sed -n 's/.* S:\([0-9]*\).*/\1/p')
    if [ "${primary_count:-0}" = "1" ] && [ "${secondary_count:-0}" = "2" ]; then
      log::ok "RS converged: 1 PRIMARY + 2 SECONDARY"
      return 0
    fi
    sleep 1
  done

  # Timeout — dump the current state to the install log so the operator
  # has something concrete to start from instead of "go ssh in and run
  # rs.status()". Common failure modes the dump distinguishes:
  #   * STARTUP / STARTUP2 / RECOVERING — initial sync still in progress
  #     (huge oplog catch-up, slow disk, network bottleneck)
  #   * (not reachable/healthy) state — keyfile bytes differ across
  #     members, or 27017 firewalled between nodes
  #   * unknown / removed — member dropped from rs.config() but mongod
  #     left running; needs an explicit rs.add()
  log::err "current rs.status() snapshot:"
  mongodb::eval_root "
    var s = rs.status();
    s.members.forEach(function(m) {
      print('  member ' + m._id + ' ' + m.name + ' = ' + m.stateStr +
            ' (health=' + m.health + ', uptime=' + m.uptime + 's' +
            (m.lastHeartbeatMessage ? ', lastHB=\"' + m.lastHeartbeatMessage + '\"' : '') + ')');
    });
    print('EVAL_OK');
  " 2>/dev/null || log::warn "could not read rs.status() — primary may be down"

  die "RS did not converge to 1 PRIMARY + 2 SECONDARY within 60s — see rs.status() snapshot above"
}

# ----- top-level entry points --------------------------------------------
# Called from install.sh on each node based on its topology row.
mongodb::setup_local_standalone() {
  log::step "Provisioning MongoDB (standalone)"
  # THP=never + systemd drop-in must land BEFORE first mongod start so
  # the limits and kernel state are in place from the very first
  # startup; otherwise mongod logs warnings on initial run + a restart
  # is needed to pick the new ulimits up.
  thp::install_disabler
  mongodb::resolve_version
  mongodb::install_package
  mongodb::write_dropin
  mongodb::_apply_keyfile_perms
  mongodb::start_service
  mongodb::bootstrap_auth standalone
  log::ok "MongoDB standalone ready"
}

mongodb::setup_replica_member() {
  log::step "Provisioning MongoDB (replica set member)"
  thp::install_disabler
  mongodb::resolve_version
  mongodb::install_package
  mongodb::write_dropin
  mongodb::_apply_keyfile_perms
  # Configure for RS BEFORE first start so the keyfile is picked up.
  # On the primary (M1) bootstrap_auth runs first to create users; on
  # secondaries we skip user creation (the RS sync will pull them).
  if [ "${ELCHI_NODE_INDEX:-1}" = "1" ]; then
    mongodb::start_service
    mongodb::bootstrap_auth rs
  else
    mongodb::configure_conf rs
    systemd::reconcile_external mongod.service mongod \
      /etc/mongod.conf \
      "${ELCHI_MONGO}/keyfile" \
      /etc/systemd/system/mongod.service.d/10-elchi.conf
    wait_for_tcp 127.0.0.1 27017 60 \
      || die "mongod did not become reachable on 127.0.0.1:27017"
  fi
  log::ok "MongoDB RS member ready"
}

mongodb::_apply_keyfile_perms() {
  local f="${ELCHI_MONGO}/keyfile"
  [ -f "$f" ] || return 0
  chown mongodb:mongodb "$f"
  chmod 0400 "$f"
  # Mongod runs as `mongodb` and must be able to traverse to the
  # keyfile path. dirs::ensure / secrets::import_from_bundle create
  # /etc/elchi/mongo as 0750 root:elchi — the elchi group is meant
  # for the elchi-stack runtime user, NOT for mongodb. Without this
  # chgrp, mongodb has zero access (other bits=0) and mongod fails
  # at startup with "errno:13 Permission denied" reading the
  # keyfile — which systemd surfaces only as "exited with status 1"
  # because the real error goes to /var/log/mongodb/mongod.log, not
  # the journal. Re-grouping to mongodb keeps the directory closed
  # to non-mongo users while letting mongod do its job.
  if [ -d "$ELCHI_MONGO" ]; then
    chgrp mongodb "$ELCHI_MONGO"
    chmod 0750 "$ELCHI_MONGO"
  fi
}

# mongodb::write_dropin — production-grade resource ceiling for the
# package-shipped mongod.service. The upstream unit ships almost no
# limits (LimitNOFILE comes from the distro default — usually 1024-65535
# depending on systemd version), so we override via drop-in.
#
# What this addresses (mongo's own production checklist):
#   * LimitNOFILE=64000  — mongod opens a file per collection + index +
#                          oplog cursor + connection. Default 1024 will
#                          surface as cryptic "too many open files" on
#                          first cluster of any size.
#   * LimitNPROC=64000   — wired-tiger uses many threads (one per
#                          connection + maintenance pool).
#   * LimitMEMLOCK=infinity — keyfile + journal mlock; without infinity
#                              they get clamped to 64KB and mongod logs
#                              "WARNING: ulimit -l ... too low".
#   * OOMScoreAdjust=-1000 — never let mongod be the OOM victim;
#                            killing the primary triggers a replicaset
#                            election storm.
#   * TasksMax=infinity   — systemd's default cgroup task limit can be
#                            as low as ~4915 on RHEL — mongod's connection
#                            pool blows past that on busy clusters.
#   * Restart=on-failure  — the upstream package unit ships NO Restart=
#                            directive, which means systemd defaults to
#                            Restart=no. A crashed mongod (assertion,
#                            segfault, kernel OOM after our -1000 cushion
#                            already failed, etc.) would just stay dead.
#                            For an RS member that's catastrophic — the
#                            primary's death silently degrades majority
#                            write capacity. Auto-restart with a 5s
#                            backoff lets the RS heartbeat re-discover
#                            the recovered member and re-sync via
#                            oplog catch-up without operator intervention.
#   * StartLimitInterval / StartLimitBurst — guard against an actually-
#                            broken instance crash-looping forever; after
#                            5 failures in 60s systemd gives up so the
#                            operator gets paged instead of disk fills.
mongodb::write_dropin() {
  install -d -m 0755 /etc/systemd/system/mongod.service.d
  cat > /etc/systemd/system/mongod.service.d/10-elchi.conf.tmp <<'EOF'
# Managed by elchi-stack installer. DO NOT EDIT BY HAND.
# Re-rendered on every install.sh; removed by uninstall.sh --purge-mongo.
[Unit]
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Restart=on-failure
RestartSec=5s
LimitNOFILE=64000
LimitNPROC=64000
LimitMEMLOCK=infinity
LimitFSIZE=infinity
LimitAS=infinity
OOMScoreAdjust=-1000
TasksMax=infinity
EOF
  install -m 0644 -o root -g root \
    /etc/systemd/system/mongod.service.d/10-elchi.conf.tmp \
    /etc/systemd/system/mongod.service.d/10-elchi.conf
  rm -f /etc/systemd/system/mongod.service.d/10-elchi.conf.tmp
  systemctl daemon-reload
  log::info "mongod systemd drop-in applied (Restart=on-failure, NOFILE=64000, MEMLOCK=infinity, OOMAdj=-1000)"
}
