#!/usr/bin/env bash
# secrets.sh — generate the cluster-wide secret material on M1 and
# persist it for both local use and bundle export.
#
# Generated once on M1 during install; M2..MN receive everything via the
# encrypted bundle. Same secrets across all nodes is the invariant —
# every backend instance must sign/verify JWTs with the same key, every
# mongo replica must auth with the same keyfile, etc.
#
# Files written:
#   ${ELCHI_ETC}/secrets.env       JWT_SECRET, MONGO_*_PASSWORD, GSLB_SECRET
#   ${ELCHI_MONGO}/keyfile         1024-byte random; mongo replica-set internal auth
#   ${ELCHI_MONGO}/root.env        mongo root username/password (M1 only, mode 0600)
#
# All files are root-owned, mode 0640 group-readable by the elchi group
# (so backend services can EnvironmentFile them) — except mongo files
# which are read by mongod as user mongodb.

# secrets::generate — idempotent. If files already exist (rerun), keep
# them. Rotation is a separate, explicit operation (operator runs
# `elchi-stack rotate-secret <name>`).
secrets::generate() {
  log::step "Generating cluster secrets"

  install -d -m 0755 -o root -g root "$ELCHI_ETC"
  install -d -m 0750 -o root -g "$ELCHI_GROUP" "$ELCHI_MONGO"

  local out="${ELCHI_ETC}/secrets.env"

  if [ -f "$out" ]; then
    log::info "${out} already exists — preserving (no rotation)"
  else
    log::info "minting fresh secrets"
    local jwt_secret mongo_app_pwd mongo_root_pwd gslb_secret grafana_pwd
    # 32-byte hex (256 bit) for everything that goes through HMAC / Argon2;
    # alnum form (avoid special chars) for mongo passwords because the
    # mongo URI parser is finicky about embedded `@:/?#%`.
    jwt_secret=$(rand_hex 32)
    mongo_app_pwd=$(rand_alnum 40)
    mongo_root_pwd=$(rand_alnum 40)
    gslb_secret=$(rand_alnum 48)
    # Grafana admin password — short alnum, easier for operators to type.
    # Operator can override via --grafana-password=... at install time.
    grafana_pwd=${ELCHI_GRAFANA_PASSWORD:-elchi-$(rand_hex 4)}

    umask 077
    cat > "${out}.tmp" <<EOF
# Auto-generated by elchi-stack installer on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT edit by hand — rotate via 'elchi-stack rotate-secret <name>'

ELCHI_JWT_SECRET=${jwt_secret}
ELCHI_GSLB_SECRET=${gslb_secret}

# Mongo credentials. The "elchi" application user has readWrite on the
# elchi DB; the "root" user is admin-scoped and only used by the installer
# during bootstrap.
ELCHI_MONGO_USERNAME=elchi
ELCHI_MONGO_PASSWORD=${mongo_app_pwd}
ELCHI_MONGO_ROOT_USERNAME=elchi-admin
ELCHI_MONGO_ROOT_PASSWORD=${mongo_root_pwd}

# Grafana admin login. Username defaults to "admin" because Grafana
# initialises the DB user from grafana.ini ONLY on first start; later
# rerun's admin_user= is ignored. Override at install time with
# --grafana-user= / --grafana-password= to set the desired values
# before the DB is initialised.
ELCHI_GRAFANA_USER=${ELCHI_GRAFANA_USER:-admin}
ELCHI_GRAFANA_PASSWORD=${grafana_pwd}
EOF
    chmod 0640 "${out}.tmp"
    chown root:"$ELCHI_GROUP" "${out}.tmp"
    mv -f "${out}.tmp" "$out"
  fi

  secrets::generate_mongo_keyfile
  secrets::write_mongo_root_env

  log::ok "secrets ready at ${out}"
}

# secrets::generate_mongo_keyfile — 1024-byte random file used by all
# mongo replica-set members for internal auth (--keyFile). Identical
# bytes across every member; bundle ships it.
secrets::generate_mongo_keyfile() {
  local keyfile="${ELCHI_MONGO}/keyfile"
  if [ -f "$keyfile" ]; then
    return 0
  fi
  log::info "generating mongo keyfile"
  umask 077
  openssl rand -base64 756 | tr -d '\n' > "${keyfile}.tmp"
  chmod 0400 "${keyfile}.tmp"
  # Mongo refuses to start if the keyfile isn't owned by the user the
  # mongod process runs as. We set this lazily — at this stage mongo may
  # not be installed yet, so the user might not exist. Defer chown to
  # mongodb::_apply_keyfile_perms() which runs after package install.
  if id mongodb >/dev/null 2>&1; then
    chown mongodb:mongodb "${keyfile}.tmp"
  fi
  mv -f "${keyfile}.tmp" "$keyfile"
}

# secrets::write_mongo_root_env — convenience env file with the root
# credentials, used by mongodb.sh during bootstrap. Mode 0600 root-only;
# never shipped in the bundle (M2/M3 don't need root access — only M1
# bootstraps the RS).
secrets::write_mongo_root_env() {
  local out="${ELCHI_MONGO}/root.env"
  [ -f "$out" ] && return 0

  # Read the values we just wrote to secrets.env.
  local user pwd
  user=$(grep -E '^ELCHI_MONGO_ROOT_USERNAME=' "${ELCHI_ETC}/secrets.env" | cut -d= -f2-)
  pwd=$(grep -E '^ELCHI_MONGO_ROOT_PASSWORD=' "${ELCHI_ETC}/secrets.env" | cut -d= -f2-)

  umask 077
  cat > "${out}.tmp" <<EOF
MONGO_ROOT_USERNAME=${user}
MONGO_ROOT_PASSWORD=${pwd}
EOF
  chmod 0600 "${out}.tmp"
  chown root:root "${out}.tmp"
  mv -f "${out}.tmp" "$out"
}

# secrets::import_from_bundle — opposite direction. M2/M3 receive the
# bundle, extract it, and call this to land secrets in the canonical
# locations. The bundle itself is the source of truth; we just copy.
secrets::import_from_bundle() {
  local bundle_dir=$1
  log::step "Importing secrets from bundle"

  install -d -m 0755 -o root -g root "$ELCHI_ETC"
  install -d -m 0750 -o root -g "$ELCHI_GROUP" "$ELCHI_MONGO"

  if [ -f "${bundle_dir}/secrets.env" ]; then
    install -m 0640 -o root -g "$ELCHI_GROUP" "${bundle_dir}/secrets.env" "${ELCHI_ETC}/secrets.env"
  else
    die "bundle missing secrets.env"
  fi

  if [ -f "${bundle_dir}/mongo/keyfile" ]; then
    install -m 0400 "${bundle_dir}/mongo/keyfile" "${ELCHI_MONGO}/keyfile"
    if id mongodb >/dev/null 2>&1; then
      chown mongodb:mongodb "${ELCHI_MONGO}/keyfile"
    fi
  fi

  log::ok "secrets imported"
}

# secrets::value <key> — read a single value from secrets.env. Used by
# config rendering modules to populate templates without sourcing the
# whole file (which would expose all vars to whatever shell scope).
secrets::value() {
  local key=$1
  grep -E "^${key}=" "${ELCHI_ETC}/secrets.env" 2>/dev/null | tail -n1 | cut -d= -f2-
}
