#!/usr/bin/env bash
# watchdog.sh — periodic health probe of every elchi-* service on this
# node, plus a minimal "is the cluster reachable?" check. Runs out of a
# systemd timer (default every 60s); writes results to journald with
# `SyslogIdentifier=elchi-watchdog` so operators can grep them out.
#
# This is the bare-metal equivalent of Helm's livenessProbe — backend
# services already have `Restart=on-failure`, so they self-recover on
# crash; the watchdog catches the slower failure mode where a process
# is alive but no longer serving traffic (deadlock, memory pressure,
# stuck on a dependency).

readonly WATCHDOG_BIN=/usr/local/bin/elchi-watchdog
readonly WATCHDOG_SERVICE=/etc/systemd/system/elchi-watchdog.service
readonly WATCHDOG_TIMER=/etc/systemd/system/elchi-watchdog.timer

watchdog::install() {
  log::step "Installing elchi-watchdog timer"

  install -d -m 0755 -o root -g root /usr/local/bin

  cat > "${WATCHDOG_BIN}.tmp" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by elchi-stack installer. Edits will be overwritten.
# Periodic health probe — runs every elchi-watchdog.timer interval.
set -euo pipefail

failed=0
warn=0

check_tcp() {
  local label=$1 host=$2 port=$3
  if (exec 3<>/dev/tcp/"$host"/"$port") 2>/dev/null; then
    exec 3<&- 3>&-
    return 0
  fi
  printf '[FAIL] %s — TCP %s:%s unreachable\n' "$label" "$host" "$port"
  return 1
}

check_unit() {
  local unit=$1
  if systemctl is-active --quiet "$unit"; then
    return 0
  fi
  printf '[FAIL] systemd unit %s is %s\n' "$unit" "$(systemctl is-active "$unit" 2>&1)"
  return 1
}

# 1. systemd state — every loaded elchi-* unit must be active.
while IFS= read -r unit; do
  [ -z "$unit" ] && continue
  case "$unit" in
    elchi-watchdog.service|elchi-watchdog.timer) continue ;;
  esac
  if ! check_unit "$unit"; then failed=$((failed+1)); fi
done < <(systemctl list-units --all --no-legend --type=service 'elchi-*' \
          | awk '$1 ~ /^elchi-/ {print $1}')

# 2. Local listener checks — read ports.full.json + topology.full.yaml.
ETC=${ELCHI_ETC:-/etc/elchi}

if [ -f "$ETC/topology.full.yaml" ]; then
  IDX=${ELCHI_NODE_INDEX:-1}
  if [ -z "${ELCHI_NODE_INDEX:-}" ]; then
    # Best-effort detection from /etc/hosts + topology
    HN=$(hostname -s)
    IDX=$(awk -v want="$HN" '
      /^  - index:/ { idx = $3 }
      $0 ~ "^    hostname: "want"$" { print idx; exit }
    ' "$ETC/topology.full.yaml")
    IDX=${IDX:-1}
  fi

  # Public Envoy + internal listener + nginx
  check_tcp "envoy-public"   127.0.0.1 "${ELCHI_PORT:-443}"            || failed=$((failed+1))
  check_tcp "envoy-internal" 127.0.0.1 8080                            || failed=$((failed+1))
  check_tcp "nginx-ui"       127.0.0.1 8081                            || warn=$((warn+1))

  # Registry on every node
  check_tcp "registry-grpc"  127.0.0.1 1870                            || failed=$((failed+1))

  # M1-only services
  if [ "$IDX" = "1" ]; then
    check_tcp "mongod"          127.0.0.1 27017                        || failed=$((failed+1))
    check_tcp "victoriametrics" 127.0.0.1 8428                         || warn=$((warn+1))
    check_tcp "otel-health"     127.0.0.1 13133                        || warn=$((warn+1))
    check_tcp "grafana"         127.0.0.1 3000                         || warn=$((warn+1))
  fi
fi

# 3. Backend registration — confirm at least one controller logged
#    "registered" recently. Catches the deadlock case where the process
#    is alive but never finished registering with the registry.
if systemctl is-active --quiet elchi-controller.service 2>/dev/null; then
  if ! journalctl -u elchi-controller.service --since '5 minutes ago' 2>/dev/null \
       | grep -q -E 'registered|RegisterController'; then
    printf '[WARN] elchi-controller has no recent registration activity (last 5m)\n'
    warn=$((warn+1))
  fi
fi

# 4. Final verdict
if [ "$failed" -gt 0 ]; then
  printf '[ELCHI-WATCHDOG] %d failure(s), %d warning(s)\n' "$failed" "$warn"
  exit 1
fi
if [ "$warn" -gt 0 ]; then
  printf '[ELCHI-WATCHDOG] healthy with %d warning(s)\n' "$warn"
  exit 0
fi
printf '[ELCHI-WATCHDOG] healthy\n'
EOF
  install -m 0755 -o root -g root "${WATCHDOG_BIN}.tmp" "$WATCHDOG_BIN"
  rm -f "${WATCHDOG_BIN}.tmp"

  cat > "${WATCHDOG_SERVICE}.tmp" <<EOF
[Unit]
Description=elchi-stack health watchdog (one-shot probe)
Documentation=https://github.com/CloudNativeWorks/elchi-archive
After=network-online.target

[Service]
Type=oneshot
Environment=ELCHI_ETC=${ELCHI_ETC}
Environment=ELCHI_PORT=${ELCHI_PORT:-443}
Environment=ELCHI_NODE_INDEX=${ELCHI_NODE_INDEX:-1}
ExecStart=${WATCHDOG_BIN}
StandardOutput=journal
StandardError=journal
SyslogIdentifier=elchi-watchdog
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
EOF
  install -m 0644 "${WATCHDOG_SERVICE}.tmp" "$WATCHDOG_SERVICE"
  rm -f "${WATCHDOG_SERVICE}.tmp"

  cat > "${WATCHDOG_TIMER}.tmp" <<EOF
[Unit]
Description=Run elchi-watchdog every minute
Documentation=https://github.com/CloudNativeWorks/elchi-archive

[Timer]
OnBootSec=2min
OnUnitActiveSec=${ELCHI_WATCHDOG_INTERVAL:-60s}
AccuracySec=10s
Persistent=true

[Install]
WantedBy=timers.target
EOF
  install -m 0644 "${WATCHDOG_TIMER}.tmp" "$WATCHDOG_TIMER"
  rm -f "${WATCHDOG_TIMER}.tmp"

  systemd::install_and_apply elchi-watchdog.timer
  log::ok "watchdog enabled (interval: ${ELCHI_WATCHDOG_INTERVAL:-60s}; tail with 'journalctl -t elchi-watchdog -f')"
}

watchdog::uninstall() {
  systemctl disable --now elchi-watchdog.timer 2>/dev/null || true
  systemctl stop elchi-watchdog.service 2>/dev/null || true
  rm -f "$WATCHDOG_TIMER" "$WATCHDOG_SERVICE" "$WATCHDOG_BIN"
  systemctl daemon-reload 2>/dev/null || true
}
