#!/usr/bin/env bash
# bump-versions.sh — bump elchi component versions everywhere they appear
# (canonical defaults + every doc / comment / example), in one shot.
#
# HOW TO USE: edit the versions in the block below, then run the script.
#   bash tools/bump-versions.sh
# ALWAYS read the diff: the replacement is textual and global, so it also hits
# prose that names a version ON PURPOSE (a changelog line, or a comment
# recording which versions a past defect involved). Clear the one-shot
# *_OLD/*_NEW pairs again once the bump has landed.
# It is a DRY RUN by default (prints a diff of what would change). When the
# preview looks right, set APPLY=1 (below) and run again to write the files.
#
# index.json is NEVER touched (it is machine-generated by the CI mirror jobs;
# only .sh/.env/.md/.html/.yml/.yaml are scanned — .json is excluded).

# ╔══════════════════════ EDIT THESE ══════════════════════╗
# Set the version(s) you want to bump. Leave a field EMPTY to leave it as-is.
# Each version is read fresh from deploy/docker/versions.env as the OLD value,
# so a stale/equal value here is just a no-op (never a downgrade).

BACKEND="v1.6.16"        # backend SEGMENT only, e.g. v1.6.1  (the -v0.14.0-envoy1.39.0
                  #   part is kept; standalone's elchi- prefix too)
UI="v1.5.23"             # UI image, e.g. v1.5.2
COREDNS="v0.1.4"        # CoreDNS / GSLB image, e.g. v0.1.5
COLLECTOR="v0.1.13"      # elchi-collector, e.g. v0.1.12

SHIELD_OLD=""     # shield has NO canonical default → set BOTH old and new
SHIELD_NEW=""     #   e.g. SHIELD_OLD="v0.4.0" SHIELD_NEW="v0.4.1"

CLIENT_OLD=""     # agent release TAG in the portal's download links
CLIENT_NEW=""     #   e.g. CLIENT_OLD="v1.6.3" CLIENT_NEW="v1.7.0"

APPLY=0           # 0 = preview (dry-run) · 1 = write the files
# ╚════════════════════════════════════════════════════════╝

set -Eeuo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)
SELF="${BASH_SOURCE[0]}"
VERSIONS_ENV="${ROOT}/deploy/docker/versions.env"

c_red=$'\033[1;31m'; c_grn=$'\033[1;32m'; c_yel=$'\033[1;33m'; c_dim=$'\033[2m'; c_rst=$'\033[0m'
info() { printf '%s\n' "$*" >&2; }
die()  { printf '%sERROR:%s %s\n' "$c_red" "$c_rst" "$*" >&2; exit 1; }

read_old() {  # read_old <versions.env var> → current value (quotes stripped)
  [ -f "$VERSIONS_ENV" ] || die "not found: $VERSIONS_ENV (run from the elchi-archive repo)"
  sed -nE "s/^$1=\"?([^\"]*)\"?.*/\1/p" "$VERSIONS_ENV" | head -n1
}

# Files we scan. index.json is excluded (only these extensions); .git and this
# script itself are skipped too.
list_files() {
  find "$ROOT" -type f \
    \( -name '*.sh' -o -name '*.env' -o -name '*.md' -o -name '*.html' -o -name '*.yml' -o -name '*.yaml' \) \
    -not -path '*/.git/*' -not -path '*/node_modules/*' 2>/dev/null \
    | grep -vF "$SELF"
}

declare -a PAIRS=() SUMMARY=()
add() {  # add <label> <old> <new>
  local label=$1 old=$2 new=$3
  [ -n "$old" ] && [ -n "$new" ] || die "internal: empty old/new for $label"
  if [ "$old" = "$new" ]; then info "${c_yel}skip${c_rst} ${label}: already ${new}"; return 0; fi
  PAIRS+=("${old}"$'\t'"${new}")
  SUMMARY+=("${label}: ${old} → ${new}")
}

# --- backend: swap ONLY the first segment of the variant ---
if [ -n "$BACKEND" ]; then
  cur=$(read_old ELCHI_DEFAULT_BACKEND_VARIANTS)
  [ -n "$cur" ] || die "could not read the backend variant from versions.env"
  case "$cur" in *,*) die "multiple backend variants (CSV) in versions.env — bump them by hand" ;; esac
  seg=$BACKEND; [[ "$seg" == v* ]] || seg="v$seg"          # normalize 1.6.1 → v1.6.1
  add backend "$cur" "${seg}-${cur#*-}"
fi
[ -n "$UI" ]        && add ui        "$(read_old ELCHI_DEFAULT_UI_VERSION)"        "$UI"
[ -n "$COREDNS" ]   && add coredns   "$(read_old ELCHI_DEFAULT_COREDNS_VERSION)"   "$COREDNS"
[ -n "$COLLECTOR" ] && add collector "$(read_old ELCHI_DEFAULT_COLLECTOR_VERSION)" "$COLLECTOR"
if [ -n "$SHIELD_NEW" ] || [ -n "$SHIELD_OLD" ]; then
  [ -n "$SHIELD_OLD" ] && [ -n "$SHIELD_NEW" ] || die "shield: set BOTH SHIELD_OLD and SHIELD_NEW"
  add shield "$SHIELD_OLD" "$SHIELD_NEW"
fi
# The agent's own release tag (elchi-client-vX.Y.Z in the portal's download
# links). It is not a component default, and the guard below keeps every
# other bump away from it, so it is bumped only when named here.
if [ -n "$CLIENT_NEW" ] || [ -n "$CLIENT_OLD" ]; then
  [ -n "$CLIENT_OLD" ] && [ -n "$CLIENT_NEW" ] || die "client: set BOTH CLIENT_OLD and CLIENT_NEW"
  add client "elchi-client-$CLIENT_OLD" "elchi-client-$CLIENT_NEW"
fi

[ "${#PAIRS[@]}" -gt 0 ] || die "nothing to bump — edit the version block at the top of this script."

info "${c_grn}Planned bumps:${c_rst}"
for s in "${SUMMARY[@]}"; do info "  • $s"; done
info ""

BUMP=$(printf '%s\n' "${PAIRS[@]}"); export BUMP   # OLD<TAB>NEW pairs for perl

changed=0
while IFS= read -r f; do
  # A version is replaced only where it stands on its own: never right after
  # elchi-client- / elchi-shield- / elchi-os-, which are RELEASE TAGS of other
  # components that happen to carry a version of the same shape. Without this
  # guard a UI bump (v1.5.15 → v1.5.21) also rewrote the portal's agent
  # download links to a release that does not exist.
  new=$(perl -0777 -pe '
    BEGIN { @P = map { [split /\t/, $_, 2] } grep { length } split /\n/, $ENV{BUMP} }
    for my $p (@P) {
      my ($o,$n) = @$p;
      if ($o =~ /^elchi-(client|shield|os)-/) { s/\Q$o\E/$n/g; next }
      s/(?<!elchi-client-)(?<!elchi-shield-)(?<!elchi-os-)\Q$o\E/$n/g;
    }
  ' "$f")
  [ "$new" = "$(cat "$f")" ] && continue
  changed=$((changed + 1)) || true
  rel=${f#"$ROOT"/}
  if [ "$APPLY" = "1" ]; then
    printf '%s\n' "$new" > "$f"
    info "${c_grn}updated${c_rst} $rel"
  else
    printf '\n%s--- %s%s\n' "$c_yel" "$rel" "$c_rst"
    diff -u "$f" - <<<"$new" | sed '1,2d' | grep -E '^[+-]' | grep -vE '^[+-]{3}' || true
  fi
done < <(list_files)

# ---- guard: variant tags that this script can never bump -------------------
# Every replacement above is keyed on the CURRENT value read from versions.env,
# which always carries the leading `v` (elchi-v1.6.15-...). A doc that wrote the
# variant WITHOUT it (elchi-1.6.14-...) was therefore invisible to every bump —
# and it is not merely stale: topology::backend_release_from_tag requires
# ^v[0-9]+\.[0-9]+\.[0-9]+ and calls die() otherwise, so an operator copying
# such an example cannot start the installer at all. Twenty-two of them sat in
# the standalone README, get.sh, install.sh, upgrade.sh --help and the portal
# until 2026-09-22. Fail loudly if the shape ever comes back.
stray=$(grep -rnE 'elchi-[0-9]+\.[0-9]+\.[0-9]+-v[0-9]' \
          --include='*.sh' --include='*.md' --include='*.html' \
          --include='*.env' --include='*.yml' --include='*.yaml' \
          "$ROOT" 2>/dev/null | grep -v '/node_modules/' || true)
if [ -n "$stray" ]; then
  info ""
  info "${c_red}Backend variant tags are missing their leading 'v' (the installer rejects these):${c_rst}"
  printf '%s\n' "$stray" | sed "s|^${ROOT}/||" >&2
fi

info ""
if [ "$APPLY" = "1" ]; then
  info "${c_grn}Done — ${changed} file(s) changed.${c_rst} index.json untouched."
  info "Review 'git diff', then cut the matching releases / run the mirror workflows."
else
  info "${c_yel}DRY RUN — ${changed} file(s) would change.${c_rst} Set APPLY=1 at the top to write. (index.json never touched.)"
fi
